---
certs:
  # Copy only these private keys and certs from ansible into the system
  requested:
    - yourmail.server.com

  # we receive our certs by scp from the main cert hosting service elsewhere
  receiver: true

  # These users have ansible-controlled ssh private keys
  # (mainly for automated backups right now)
  sshKeysForUsers:
    - root
